# Generated by Django 3.2.9 on 2021-12-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('driver_pic', models.ImageField(upload_to='media/driver/pics/')),
                ('driving_licence', models.ImageField(upload_to='media/driver/licences/')),
                ('salary', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('nid', models.ImageField(upload_to='media/driver/nid/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Operation', 'Operation'), ('CRO', 'CRO'), ('GPS', 'GPS'), ('Ambulance', 'Ambulance'), ('Pool', 'Pool'), ('Delivery', 'Delivery')], max_length=100)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('register_number', models.CharField(max_length=100)),
                ('chasis_no', models.CharField(max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('item', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('reference', models.FileField(blank=True, null=True, upload_to='referance/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('overtime', models.IntegerField(blank=True, null=True)),
                ('trip_start', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('trip_end', models.DateField(blank=True, null=True)),
                ('email', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.vehicle')),
            ],
        ),
    ]
