# Generated by Django 3.2.9 on 2021-12-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('contact', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('employee_id', models.CharField(max_length=128, null=True, unique=True)),
                ('designation', models.CharField(choices=[('', 'SELECT OPTIONS'), ('Engineer', 'Engineer'), ('Manager', 'Manager'), ('Quality Controller', 'Quality Controller'), ('Consultant', 'Consultant')], max_length=128, null=True)),
                ('joining_date', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('branch', models.CharField(max_length=128, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(default='default.jpg', null=True, upload_to='profile_pic')),
                ('percent', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128, null=True)),
                ('task_progress', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=12, null=True)),
                ('job_status', models.CharField(choices=[('Running', 'Running'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], max_length=12, null=True)),
                ('job_type', models.CharField(choices=[('Part Time', 'Part Time'), ('Permanent', 'Permanent'), ('Probation', 'Probation')], max_length=12, null=True)),
                ('salary_to_be_paid', models.CharField(max_length=128, null=True)),
                ('overtime_amount', models.CharField(max_length=128, null=True)),
                ('overtime', models.IntegerField(blank=True, null=True)),
                ('salary_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
        ),
    ]
